<?xml version="1.0"?>
<robot name="macroed" xmlns:xacro="http://ros.org/wiki/xacro">
   <!-- Defining the colors used in this robot -->
    <material name="Black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="White">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="Blue">
        <color rgba="0 0 1 1"/>
    </material>

    <material name="Red">
        <color rgba="1 0 0 1"/>
    </material>
    
    <material name="Green">
        <color rgba="0 1 0 1"/>
    </material>

    <!-- Constants -->
    
    <xacro:property name="ToRad" value="0.01745327777"/>
    <xacro:property name="X_Offset_1" value="-0.0225"/>
    <xacro:property name="Z_Offset_1" value="0.13397459622"/>
    
    <!-- link1 properties -->
    <xacro:property name="link1_width" value="0.01" />
    <xacro:property name="link1_len" value="0.094414" />
    <xacro:property name="link1_len_pj" value="0.083" />
    <!-- link2 properties -->
    <xacro:property name="link2_width" value="0.01" />
    <xacro:property name="link2_len" value="0.105" />

    <!-- link3 properties -->
    <xacro:property name="link3_width" value="0.01" />
    <xacro:property name="link3_len" value="0.0388973006776" />

    <!-- link4 properties -->
    <xacro:property name="link4_width" value="0.02" />
    <xacro:property name="link4_len" value="0.1525" />

    <!-- link5 properties -->
    <xacro:property name="link5_width" value="0.02" />
    <xacro:property name="link5_len" value="0.03" />

    <!-- link6 properties -->
    <xacro:property name="link6_width" value="0.02" />
    <xacro:property name="link6_len" value="0.04" />

    <!-- Inertial matrix -->
    <xacro:macro name="inertial_matrix" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>


  

    <!-- /////////////////////////////////////   BASE LINK    ////////////////////////////////////////////// -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.02 0.02 0.001" />
            </geometry>
            <material name="White" />
        </visual>
    </link>

    <joint name="joint1" type="revolute">
        <parent link="base_link"/>
        <child link="link1"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="300" velocity="1" lower="-2.96" upper="2.96"/>
        <dynamics damping="50" friction="1"/>
    </joint>

    <!-- /////////////////////////////////////   LINK1  ////////////////////////////////////////////// -->
    <link name="link1" >
        <visual>
            <origin xyz="${X_Offset_1} 0 ${link1_len_pj/2} " rpy="0 -${28.465*ToRad} 0" />
            <geometry>
                <cylinder radius="${link1_width}" length="${link1_len}"/>
            </geometry>
            <material name="Blue" />
        </visual>
    
        <xacro:inertial_matrix mass="1"/>
    </link>
    
    <joint name="joint2" type="revolute">
        <parent link="link1"/>
        <child link="link2"/>
        <origin xyz="${X_Offset_1*2} 0 ${link1_len_pj}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="300" velocity="1" lower="-2.96" upper="2.96"/>
        <dynamics damping="50" friction="1"/>
    </joint>
 	
    <!-- /////////////////////////////////////   LINK2  ////////////////////////////////////////////// -->
    <link name="link2" >
        <visual>
            <origin xyz="0 0 ${ link2_len/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${link2_width}" length="${link2_len}"/>
            </geometry>
            <material name="Red" />
        </visual>
    
        <xacro:inertial_matrix mass="1"/>
    </link>
    <joint name="joint3" type="revolute">
        <parent link="link2"/>
        <child link="link3"/>
        <origin xyz="0 0  ${link2_len}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="300" velocity="1" lower="-2.96" upper="2.96"/>
        <dynamics damping="50" friction="1"/>
    </joint>  

    <!-- /////////////////////////////////////   LINK3  ////////////////////////////////////////////// -->
    <link name="link3" >
        <visual>
            <origin xyz="-0.0185 0 0.006" rpy="0 -${72.031*ToRad} 0" />
            <geometry>
                <cylinder radius="${link3_width}" length="${link3_len}"/>
            </geometry>
            <material name="Blue" />
        </visual>
    
        <xacro:inertial_matrix mass="1"/>
    </link>
    <joint name="joint4" type="revolute">
        <parent link="link3"/>
        <child link="link4"/>
        <origin xyz="-0.037 0 0.012" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <limit effort="300" velocity="1" lower="-2.96" upper="2.96"/>
        <dynamics damping="50" friction="1"/>
    </joint> 
    
    <!-- /////////////////////////////////////   LINK4  ////////////////////////////////////////////// -->
    <link name="link4" >
        <visual>
            <origin xyz="-${link4_len/2} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${link4_len} ${link4_width} ${link4_width}"/>
            </geometry>
            <material name="Red" />
        </visual>
    
        <xacro:inertial_matrix mass="1"/>
    </link>   
    <joint name="joint5" type="revolute">
        <parent link="link4"/>
        <child link="link5"/>
        <origin xyz="-${link4_len} 0 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="300" velocity="1" lower="-2.96" upper="2.96"/>
        <dynamics damping="50" friction="1"/>
    </joint>     

    <!-- /////////////////////////////////////   LINK5  ////////////////////////////////////////////// -->
    <link name="link5" >
        <visual>
            <origin xyz="0 0 0" rpy="${90*ToRad} 0 0" />
            <geometry>
                <cylinder radius="${link5_width}" length="${link5_len}"/>
            </geometry>
            <material name="Blue" />
        </visual>
    
        <xacro:inertial_matrix mass="1"/>
    </link>     
    <joint name="joint6" type="revolute">
        <parent link="link5"/>
        <child link="link6"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="300" velocity="1" lower="-2.96" upper="2.96"/>
        <dynamics damping="50" friction="1"/>
    </joint>     
    
    <!-- /////////////////////////////////////   LINK6  ////////////////////////////////////////////// -->
    <link name="link6" >
        <visual>
            <origin xyz="0 0 -${link6_len/2}" rpy="0 ${90*ToRad} 0" />
            <geometry>
                <box size="${link6_len} ${link6_width} ${link6_width}"/>
            </geometry>
            <material name="Green" />
        </visual>
    
        <xacro:inertial_matrix mass="1"/>
    </link>     
    
    
    
    
    
     
</robot>
