#!/usr/bin/python3.8
# from curses import window

from typing import ValuesView
import PySimpleGUI as GUI
import TFListener as tf 
import time

import ServoControl as sc


from threading import Thread


poseListener = tf.TFListener()

servoControl = sc.ServoControl()    

servoControl.HomeRobot()

def InitGUI():
    layout = [
        
        [GUI.Text('X:'),GUI.Text('0',key='lbX'),GUI.Text('Y:'),GUI.Text('0',key='lbY'),GUI.Text('Z:'),GUI.Text('0',key='lbZ')],
        [GUI.Text('RX:'),GUI.Text('0',key='lbRX'),GUI.Text('RY:'),GUI.Text('0',key='lbRY'),GUI.Text('RZ:'),GUI.Text('0',key='lbRZ')],
        [GUI.InputText()],
        [GUI.Button('X', key='btX'),GUI.Button('Y', key='btY'),GUI.Button('Z', key='btZ'),\
        GUI.Button('RX', key='btRX'),GUI.Button('RY', key='btRY'),GUI.Button('RZ', key='btRZ')],

        
        [GUI.Text('J1:'),GUI.Text('0',key='lbJ1'),GUI.Text('J2:'),GUI.Text('0',key='lbJ2'),GUI.Text('J3:'),GUI.Text('0',key='lbJ3'),\
        GUI.Text('J4:'),GUI.Text('0',key='lbJ4'),GUI.Text('J5:'),GUI.Text('0',key='lbJ5'),GUI.Text('J6:'),GUI.Text('0',key='lbJ6')],
        [GUI.InputText()],
       
        [GUI.Button('J1', key='btJ1'),GUI.Button('J2', key='btJ2'),GUI.Button('J3', key='btJ3'),\
        GUI.Button('J4', key='btJ4'),GUI.Button('J5', key='btJ5'),GUI.Button('J6', key='btJ6')],
        
        [GUI.Button('Home', key='btHome')]
        ]
    window = GUI.Window('Title', layout, finalize=True)

    btX = window['btX']
    btY = window['btY']
    btZ = window['btZ']

    btRX = window['btRX']
    btRY = window['btRY']
    btRZ = window['btRZ']

    btJ1 = window['btJ1']
    btJ2 = window['btJ2']
    btJ3 = window['btJ3']
    btJ4 = window['btJ4']
    btJ5 = window['btJ5']
    btJ6 = window['btJ6']

    btX.bind('<ButtonPress>', " Press", propagate=False)
    btY.bind('<ButtonPress>', " Press", propagate=False)
    btZ.bind('<ButtonPress>', " Press", propagate=False)

    btRX.bind('<ButtonPress>', " Press", propagate=False)
    btRY.bind('<ButtonPress>', " Press", propagate=False)
    btRZ.bind('<ButtonPress>', " Press", propagate=False)

    btJ1.bind('<ButtonPress>', " Press", propagate=False)
    btJ2.bind('<ButtonPress>', " Press", propagate=False)
    btJ3.bind('<ButtonPress>', " Press", propagate=False)
    btJ4.bind('<ButtonPress>', " Press", propagate=False)
    btJ5.bind('<ButtonPress>', " Press", propagate=False)
    btJ6.bind('<ButtonPress>', " Press", propagate=False)

    btX.bind('<ButtonRelease>', " Release", propagate=False)
    btY.bind('<ButtonRelease>', " Release", propagate=False)
    btZ.bind('<ButtonRelease>', " Release", propagate=False)

    btRX.bind('<ButtonRelease>', " Release", propagate=False)
    btRY.bind('<ButtonRelease>', " Release", propagate=False)
    btRZ.bind('<ButtonRelease>', " Release", propagate=False)

    btJ1.bind('<ButtonRelease>', " Release", propagate=False)
    btJ2.bind('<ButtonRelease>', " Release", propagate=False)
    btJ3.bind('<ButtonRelease>', " Release", propagate=False)
    btJ4.bind('<ButtonRelease>', " Release", propagate=False)
    btJ5.bind('<ButtonRelease>', " Release", propagate=False)
    btJ6.bind('<ButtonRelease>', " Release", propagate=False)

    return window
  
def GUIListener( window):
    XYZOffset1 = 0
    jointOffset2 = 0
    while True:
        event, values = window.read(timeout = 10)
        try:
            XYZOffset1 = float(values[0])   
        except:
            XYZOffset1 = 0

        try:
            jointOffset2 = float(values[1])   
        except:
            jointOffset2 = 0



        if event == GUI.WIN_CLOSED:
            break
        if event !='__TIMEOUT__':
            print(event)

        if event =='btHome':   
            poseListener.homeRobot()


        # Offset XYZ
        if event == 'btX Press':
            poseListener.tool_move(XYZOffset1,0)
        if event == 'btY Press':
            poseListener.tool_move(XYZOffset1,1)          
        if event == 'btZ Press':
            poseListener.tool_move(XYZOffset1,2)
        if event == 'btRX Press':
            poseListener.tool_move(XYZOffset1,3)
        if event == 'btRY Press':
            poseListener.tool_move(XYZOffset1,4)
        if event == 'btRZ Press':
            poseListener.tool_move(XYZOffset1,5)

        # Offset Joint
        if event == 'btJ1 Press':
            poseListener.offsetJoint(1,jointOffset2)
        if event == 'btJ2 Press':
            poseListener.offsetJoint(2,jointOffset2)            
        if event == 'btJ3 Press':
            poseListener.offsetJoint(3,jointOffset2)
        if event == 'btJ4 Press':
            poseListener.offsetJoint(4,jointOffset2)
        if event == 'btJ5 Press':
            poseListener.offsetJoint(5,jointOffset2)
        if event == 'btJ6 Press':
            poseListener.offsetJoint(6,jointOffset2)


        

       
         

        window['lbX'].update(poseListener.X)
        window['lbY'].update(poseListener.Y)
        window['lbZ'].update(poseListener.Z)
        window['lbRX'].update(poseListener.RX)
        window['lbRY'].update(poseListener.RY)
        window['lbRZ'].update(poseListener.RZ)
        window['lbJ1'].update(poseListener.J1)
        window['lbJ2'].update(poseListener.J2)
        window['lbJ3'].update(poseListener.J3)
        window['lbJ4'].update(poseListener.J4)
        window['lbJ5'].update(poseListener.J5)
        window['lbJ6'].update(poseListener.J6)

        outputArray = [poseListener.J1,poseListener.J2, poseListener.J3,poseListener.J4,poseListener.J5,poseListener.J6]
        
        # pass ros angle to servo.
        servoControl.MoveJ1(outputArray[0])
        servoControl.MoveJ2(outputArray[1])
        servoControl.MoveJ3(outputArray[2])
        servoControl.MoveJ4(outputArray[3])
        servoControl.MoveJ5(outputArray[4])
        servoControl.MoveJ6(outputArray[5])

        poseListener.ValveOn()
        # time.sleep(5)
        poseListener.ValveOff()
        # time.sleep(5)

        time.sleep(0.05)

def main():
  
    poseListener.Initialize()

    window = InitGUI()
  
    while True:
        GUIListener(window)

if __name__ == "__main__":
    main()
